---
title: "ID529: Data Management and Analytic Workflows in R"
format: html
---

## Welcome!

Details:

 * Find the course on [my.harvard.edu](https://courses.my.harvard.edu/psp/courses/EMPLOYEE/EMPL/h/?tab=HU_CLASS_SEARCH&SearchReqJSON=%7B%22PageNumber%22%3A1%2C%22PageSize%22%3A%22%22%2C%22SortOrder%22%3A%5B%22SCORE%22%5D%2C%22Facets%22%3A%5B%5D%2C%22Category%22%3A%22HU_SCL_SCHEDULED_BRACKETED_COURSES%22%2C%22SearchPropertiesInResults%22%3Atrue%2C%22FacetsInResults%22%3Atrue%2C%22SaveRecent%22%3Afalse%2C%22TopN%22%3A%22%22%2C%22ExcludeBracketed%22%3Atrue%2C%22SearchText%22%3A%22ID529%22%2C%22DeepLink%22%3Afalse%7D) 
 * Course Hours: 1:30-5:30 PM 
 * Classroom: Our classroom will be Kresge 502. 
 * Course Dates: 
   - Monday January 12th - Friday January 16th, 
   - Tuesday January 20th - Friday January 23rd, 2026 
 * Office Hours: 
   - 12:00 PM – 1:00 PM on Wednesday January 14th
   - 11:00 AM – 12:00 PM on Thursday January 15th, Wednesday January 21st, Thursday January 22nd 

 * Limit 60 students, priority for Population Health Science (PHS) students

### Course Description 

<div class="alert alert-secondary">
*Data Management and Analytic Workflows in R* will introduce students to R
programming and modern data management and analysis workflows applied to
examples from population health science. Throughout, we will emphasize
reproducibility, open science, data visualization, and dynamic document
generation. Specific skills learned will include the use of the RStudio
integrated development environment, tidy data management practices/workflows,
how to get help in programming, and how to use GitHub to track changes in code,
disseminate professional work, and integrate feedback. Coursework will consist
of lectures, in-class group work, homework, peer assessment, and time for
discussion. This course complements graduate-level courses in statistics and
quantitative research methods by helping students develop practical skills for
conducting independent research incorporating modern data science principles.
Students completing this course will have a solid foundation enabling them to
handle complex data management tasks and data communication skills for research
and professional work.
</div>

### Student Testimonials 

Students were very happy with how the class went last winter!  Here are some student testionials, shared with students' permission: 

::: {.grid}
:::{.g-col-4}
<p class="alert alert-info">
"I really enjoyed the whole learning experience in this course."
</p>
:::

:::{.g-col-4}
<div class="alert alert-info">
"Very informative and useful. As a someone who has his first exposure to R, I learned a lot."
</div>
:::

:::{.g-col-4}
<div class="alert alert-info">
"The teaching team were very supportive and very promptly acted on feedback."
</div>
:::

:::{.g-col-4}
<div class="alert alert-info">
"It was wonderful! Totally friendly to R beginners. And got a lot positive feedback and encouragement from the teaching team! Shout out to their efforts!"
</div>
:::


:::{.g-col-4}
<div class="alert alert-info">
"Slides that are managed so well! Unparellel instructional team! You are so friendly and patient! I really love that homeworks are managed through Github!"
</div>
:::


:::{.g-col-4}
<div class="alert alert-info">
"I loved this class!! So much was covered but it didn't feel overwhelming at the same time because the expectation was that we all came in with different levels of experience with R and that these are resources we are introduced to and can always come back to."
</div>
:::

:::{.g-col-4}
<div class="alert alert-info">
This course has been excellent! It was exactly what I was looking for - I wanted to kind of catch up to my peers who have had experience in R and learn best practices. R feels a lot less intimidating now, and I know where to look for help. Thank you! 
</div>
:::

:::{.g-col-4}
<div class="alert alert-info">
I think this course was great. I am happy that all levels of R were welcome in the course. I felt like I could just do beginner level work and still get a good grade. 
</div>
:::

:::{.g-col-4}
<div class="alert alert-info">
Extremely well. I think it will be the most recommended course for whoever wants to gain skills in data management and analysis
</div>
:::

:::

And lots more 🙂

### Instructional Team 

:::{.grid}
:::{.g-col-6}
<div class="alert alert-success">
  <b>Christian Testa</b><br>
    2nd Year PhD Student<br>
    Department of Biostatistics<br>
    {{< fa envelope >}} <ctesta@hsph.harvard.edu><br>
    {{< fa brands github >}} [GitHub](https://github.com/ctesta01) <br>
    {{< fa earth-asia >}} [Website](https://ctesta.com) <br>
    {{< fa brands mastodon >}} [Mastodon](https://fediscience.org/@ctesta) <br>
    {{< fa book >}} [Google Scholar](https://scholar.google.com/citations?hl=en&user=_9VD8mkAAAAJ)
</div>
:::
:::{.g-col-6}
  <div class="alert alert-success">
  <b>Dean Marengi</b><br>
    4th Year PhD Student<br>
    Department of Environmental Health<br>
    {{< fa envelope >}} <dean_marengi@g.harvard.edu> <br>
    {{< fa book >}} [Google Scholar](https://scholar.google.com/citations?user=334cCvsAAAAJ&hl=en)
  </div>
:::
:::{.g-col-12}
  <div class="alert alert-success">
  <b>Jarvis Chen</b><br>
    Senior Lecturer<br>
    Department of Social and Behavioral Sciences<br>
    {{< fa envelope >}} <jarvis@hsph.harvard.edu> <br> 
    {{< fa earth-asia >}} <https://www.hsph.harvard.edu/profile/jarvischen/> <br> 
    {{< fa book >}} [Google Scholar](https://scholar.google.com/citations?user=CEhmeoYAAAAJ&hl=en&oi=ao)
  </div>
:::
:::
    
### Teaching Alumnus

  * <b>[Amanda Hernandez](https://github.com/amandabhernandez) </b> was an
  amazing masters student in Environmental Health
  who helped us develop a lot of material and helped teach the course in
  Winter Session 2023. 


### Go on to syllabus 

<div class='highlight'>
<div class='bs-callout bs-callout-warning'>
<a href="/about.html">Click here to go to the syllabus.</a>
</div>
</div>

### Jump into the Curriculum 

- [Day 1 — Monday January 12th, 2026](/day1.html)
- [Day 2 — Tuesday January 13th, 2026](/day2.html)
- [Day 3 — Wednesday January 14th, 2026](/day3.html)
- [Day 4 — Thursday January 15th, 2026](/day4.html) 
- [Day 5 — Friday January 16th, 2026](/day5.html)
- (MLK Jr. Day on Monday January 14th) 
- [Day 6 — Tuesday January 20th, 2026](/day6.html) 
- [Day 7 — Wednesday January 21st, 2026](/day7.html) 
- [Day 8 — Thursday January 22nd, 2026](/day8.html) 
- [Day 9 — Friday January 23rd, 2026](/day9.html)

<iframe>
